# Generated by scripts/generate_event_codes.py in ogd-standards from the event standard.
# Do not edit by hand. Regenerate it when the standard changes.
# gdlint:disable=max-line-length
class_name OGDEvents
## Event codes from the OpenGameData event standard, grouped by category and family.
## Game-specific events can use the X900-X999 codes of any block, or the 9000 block.

enum Meta {
	## The application is launched or started.
	APPLICATION_LIFECYCLE_APPLICATION_LAUNCHED = 1000,
	## The application is closed or terminated.
	APPLICATION_LIFECYCLE_APPLICATION_TERMINATED = 1001,
	## The application becomes the active foreground application.
	APPLICATION_LIFECYCLE_APPLICATION_FOREGROUNDED = 1002,
	## The application leaves the foreground.
	APPLICATION_LIFECYCLE_APPLICATION_BACKGROUNDED = 1003,
	## A gameplay session begins.
	SESSION_LIFECYCLE_SESSION_STARTED = 1100,
	## The gameplay session is paused.
	SESSION_LIFECYCLE_SESSION_PAUSED = 1101,
	## A paused gameplay session resumes.
	SESSION_LIFECYCLE_SESSION_RESUMED = 1102,
	## The gameplay session ends.
	SESSION_LIFECYCLE_SESSION_ENDED = 1103,
	## The gameplay session is reset.
	SESSION_LIFECYCLE_SESSION_RESET = 1104,
	## The player opens the main application menu.
	MENU_APPLICATION_NAVIGATION_OPEN_MAIN_MENU = 1200,
	## The player closes the main application menu.
	MENU_APPLICATION_NAVIGATION_CLOSE_MAIN_MENU = 1201,
	## The player moves between application-level menu screens without selecting an option.
	MENU_APPLICATION_NAVIGATION_NAVIGATE_MENU_SCREEN = 1202,
	## The player returns to the previous menu screen.
	MENU_APPLICATION_NAVIGATION_RETURN_TO_PREVIOUS_MENU = 1203,
	## The player selects an application-level menu option.
	MENU_APPLICATION_NAVIGATION_SELECT_MENU_OPTION = 1204,
	## The player opens the settings screen.
	SETTINGS_CONFIGURATION_OPEN_SETTINGS = 1300,
	## The player changes a setting value.
	SETTINGS_CONFIGURATION_CHANGE_SETTING = 1301,
	## Settings are reset to defaults.
	SETTINGS_CONFIGURATION_RESET_SETTINGS = 1302,
	## The settings screen is closed.
	SETTINGS_CONFIGURATION_CLOSE_SETTINGS = 1303,
	## A player profile is selected.
	PROFILE_IDENTITY_SELECT_PROFILE = 1400,
	## A player logs in.
	PROFILE_IDENTITY_LOGIN = 1401,
	## A player logs out.
	PROFILE_IDENTITY_LOGOUT = 1402,
	## A new player profile is created.
	PROFILE_IDENTITY_CREATE_PROFILE = 1403,
	## A player profile is deleted.
	PROFILE_IDENTITY_DELETE_PROFILE = 1404,
	## Application-level loading begins.
	LOADING_APPLICATION_TRANSITIONS_START_LOADING = 1500,
	## Application-level loading completes.
	LOADING_APPLICATION_TRANSITIONS_LOADING_COMPLETE = 1501,
	## A non-gameplay application transition begins.
	LOADING_APPLICATION_TRANSITIONS_START_APPLICATION_TRANSITION = 1502,
	## A non-gameplay application transition completes.
	LOADING_APPLICATION_TRANSITIONS_COMPLETE_APPLICATION_TRANSITION = 1503,
	## The player enters a matchmaking process to be placed into a gameplay session.
	MATCHMAKING_ENTER_MATCHMAKING = 1600,
	## The player leaves a matchmaking process before being placed into a session.
	MATCHMAKING_EXIT_MATCHMAKING = 1601,
	## The system identifies a compatible match for the player.
	MATCHMAKING_MATCHMAKING_MATCH_FOUND = 1602,
	## The player is assigned to a gameplay session or pre-game lobby.
	MATCHMAKING_MATCHMAKING_ASSIGNMENT = 1603,
	## The matchmaking process ends without forming a match.
	MATCHMAKING_MATCHMAKING_TIMEOUT = 1604,
}

enum NarrativeCommunication {
	## Narration sequence becomes available/active.
	NARRATION_ENTER_NARRATION = 2001,
	## Narration sequence is exited and no longer active.
	NARRATION_EXIT_NARRATION = 2002,
	## Narration ends before completion due to interruption or quit.
	NARRATION_ABANDON_NARRATION = 2003,
	## Narration begins advancing/playing.
	NARRATION_START_NARRATION = 2010,
	## Narration reaches its intended end without skipping/abandoning.
	NARRATION_COMPLETE_NARRATION = 2011,
	## Narration display is cleared or no longer available.
	NARRATION_CLEAR_NARRATION = 2012,
	## Narration advances to the next unit (player or system driven).
	NARRATION_ADVANCE_NARRATION = 2013,
	## Narration is skipped to the end (or past remaining content).
	NARRATION_SKIP_NARRATION = 2014,
	## Dialog sequence becomes available/active.
	DIALOG_ENTER_DIALOG = 2101,
	## Dialog sequence is exited and no longer active.
	DIALOG_EXIT_DIALOG = 2102,
	## Dialog ends before completion due to interruption or quit.
	DIALOG_ABANDON_DIALOG = 2103,
	## Dialog begins advancing/playing.
	DIALOG_START_DIALOG = 2110,
	## Dialog reaches its intended end (animation/playback finished).
	DIALOG_COMPLETE_DIALOG = 2111,
	## Dialog display is cleared or no longer available.
	DIALOG_CLEAR_DIALOG = 2112,
	## Dialog advances to the next unit (typically player action).
	DIALOG_ADVANCE_DIALOG = 2113,
	## Dialog is skipped to the end (typically player action).
	DIALOG_SKIP_DIALOG = 2114,
	## Dialog choice options are displayed to the player.
	DIALOG_CHOICES_DISPLAYED = 2115,
	## A dialog choice is selected.
	DIALOG_CHOICE_SELECTED = 2116,
	## Player begins a free-text or open response input.
	DIALOG_FREE_RESPONSE_INITIATED = 2117,
	## Player submits a dialog response (choice or free response).
	DIALOG_SUBMIT_RESPONSE = 2118,
	## Tutorial sequence becomes available/active.
	TUTORIALIZATION_ENTER_TUTORIAL = 2201,
	## Tutorial sequence is exited and no longer active.
	TUTORIALIZATION_EXIT_TUTORIAL = 2202,
	## Tutorial ends before completion due to interruption or quit.
	TUTORIALIZATION_ABANDON_TUTORIAL = 2203,
	## Tutorial begins advancing/playing.
	TUTORIALIZATION_START_TUTORIAL = 2210,
	## Tutorial reaches its intended end.
	TUTORIALIZATION_COMPLETE_TUTORIAL = 2211,
	## Tutorial display is cleared or no longer available.
	TUTORIALIZATION_CLEAR_TUTORIAL = 2212,
	## Tutorial advances to the next unit.
	TUTORIALIZATION_ADVANCE_TUTORIAL = 2213,
	## Tutorial is skipped to the end.
	TUTORIALIZATION_SKIP_TUTORIAL = 2214,
	## Positive feedback sequence begins.
	POSITIVE_FEEDBACK_START_POSITIVE_FEEDBACK = 2310,
	## Positive feedback sequence completes naturally.
	POSITIVE_FEEDBACK_COMPLETE_POSITIVE_FEEDBACK = 2311,
	## Positive feedback display is cleared or no longer available.
	POSITIVE_FEEDBACK_CLEAR_POSITIVE_FEEDBACK = 2312,
	## Positive feedback advances to the next unit (if multi-part).
	POSITIVE_FEEDBACK_ADVANCE_POSITIVE_FEEDBACK = 2313,
	## Positive feedback is skipped to the end.
	POSITIVE_FEEDBACK_SKIP_POSITIVE_FEEDBACK = 2314,
	## Negative feedback sequence begins.
	NEGATIVE_FEEDBACK_START_NEGATIVE_FEEDBACK = 2410,
	## Negative feedback sequence completes naturally.
	NEGATIVE_FEEDBACK_COMPLETE_NEGATIVE_FEEDBACK = 2411,
	## Negative feedback display is cleared or no longer available.
	NEGATIVE_FEEDBACK_CLEAR_NEGATIVE_FEEDBACK = 2412,
	## Negative feedback advances to the next unit (if multi-part).
	NEGATIVE_FEEDBACK_ADVANCE_NEGATIVE_FEEDBACK = 2413,
	## Negative feedback is skipped to the end.
	NEGATIVE_FEEDBACK_SKIP_NEGATIVE_FEEDBACK = 2414,
	## Hint/help sequence begins.
	HINTING_START_HINT = 2510,
	## Hint/help sequence completes naturally.
	HINTING_COMPLETE_HINT = 2511,
	## Hint/help display is cleared or no longer available.
	HINTING_CLEAR_HINT = 2512,
	## Hint/help advances to the next unit.
	HINTING_ADVANCE_HINT = 2513,
	## Hint/help is skipped to the end.
	HINTING_SKIP_HINT = 2514,
	## Player requests a hint/help (player-initiated request).
	HINTING_REQUEST_HINT = 2515,
}

enum Segmentation {
	## A global gameplay segment begins.
	GLOBAL_GAMEPLAY_SEGMENTS_START_GLOBAL_SEGMENT = 3000,
	## A global gameplay segment ends.
	GLOBAL_GAMEPLAY_SEGMENTS_END_GLOBAL_SEGMENT = 3001,
	## Global gameplay segment exits without completion.
	GLOBAL_GAMEPLAY_SEGMENTS_ABANDON_GLOBAL_SEGMENT = 3002,
	## Global gameplay segment resumes/restores.
	GLOBAL_GAMEPLAY_SEGMENTS_RESUME_GLOBAL_SEGMENT = 3003,
	## The current exclusive segment begins (e.g., level start).
	EXCLUSIVE_TOPOLOGICAL_SEGMENTS_START_SEGMENT_LEVEL = 3100,
	## The current exclusive segment ends (e.g., level complete/exit).
	EXCLUSIVE_TOPOLOGICAL_SEGMENTS_END_SEGMENT_LEVEL = 3101,
	## Exclusive segment exits without completion.
	EXCLUSIVE_TOPOLOGICAL_SEGMENTS_ABANDON_SEGMENT_LEVEL = 3102,
	## Exclusive segment resumes/restores.
	EXCLUSIVE_TOPOLOGICAL_SEGMENTS_RESUME_SEGMENT_LEVEL = 3103,
	## A subsegment within the exclusive segment begins (e.g., round start).
	EXCLUSIVE_TOPOLOGICAL_SEGMENTS_START_SUBSEGMENT_ROUND = 3110,
	## A subsegment within the exclusive segment ends.
	EXCLUSIVE_TOPOLOGICAL_SEGMENTS_END_SUBSEGMENT_ROUND = 3111,
	## Subsegment exits without completion.
	EXCLUSIVE_TOPOLOGICAL_SEGMENTS_ABANDON_SUBSEGMENT_ROUND = 3112,
	## Subsegment resumes/restores.
	EXCLUSIVE_TOPOLOGICAL_SEGMENTS_RESUME_SUBSEGMENT_ROUND = 3113,
	## A non-exclusive segment begins.
	NON_EXCLUSIVE_SEGMENTS_START_SEGMENT_QUEST_OBJECTIVE = 3200,
	## A non-exclusive segment ends/completes.
	NON_EXCLUSIVE_SEGMENTS_END_SEGMENT_QUEST_OBJECTIVE = 3201,
	## A non-exclusive segment is abandoned.
	NON_EXCLUSIVE_SEGMENTS_ABANDON_SEGMENT_QUEST_OBJECTIVE = 3202,
	## A non-exclusive segment resumes/restores.
	NON_EXCLUSIVE_SEGMENTS_RESUME_SEGMENT_QUEST_OBJECTIVE = 3203,
	## Player enters a spatial region/area.
	SPATIAL_REGIONS_ENTER_REGION = 3300,
	## Player exits a spatial region/area.
	SPATIAL_REGIONS_EXIT_REGION = 3301,
	## Region is exited via interruption/quit (without normal exit).
	SPATIAL_REGIONS_ABANDON_REGION = 3302,
	## Player returns to a region via restore/resume.
	SPATIAL_REGIONS_RESUME_REGION = 3303,
}

enum PlayerAction {
	## The player submits or commits a response or action.
	UNIVERSAL_PLAYER_ACTIONS_SUBMIT_RESPONSE = 4000,
	## The player cancels or withdraws a previously initiated response.
	UNIVERSAL_PLAYER_ACTIONS_CANCEL_SUBMISSION = 4001,
	## The player picks up or grabs an object.
	PUZZLE_CONSTRUCTED_RESPONSE_PICK_UP_OBJECT = 4100,
	## The player places an object in a valid location/configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_PLACE_OBJECT_VALID = 4101,
	## The player attempts to place an object in an invalid location/configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_PLACE_OBJECT_INVALID = 4102,
	## The player removes an object from its current placement.
	PUZZLE_CONSTRUCTED_RESPONSE_REMOVE_OBJECT = 4103,
	## The player begins rotating an object.
	PUZZLE_CONSTRUCTED_RESPONSE_START_ROTATE_OBJECT = 4104,
	## The player finishes rotating an object.
	PUZZLE_CONSTRUCTED_RESPONSE_END_ROTATE_OBJECT = 4105,
	## The player previews a potential object placement.
	PUZZLE_CONSTRUCTED_RESPONSE_PREVIEW_PLACEMENT = 4106,
	## The player modifies an object’s state or configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_MODIFY_OBJECT = 4107,
	## The player selects an object.
	POINT_AND_CLICK_SELECT_OBJECT = 4200,
	## The player deselects an object.
	POINT_AND_CLICK_DESELECT_OBJECT = 4201,
	## The player activates or triggers an object.
	POINT_AND_CLICK_ACTIVATE_OBJECT = 4202,
	## The player changes an object’s state through interaction.
	POINT_AND_CLICK_CHANGE_OBJECT_STATE = 4203,
	## The player inspects or examines an object.
	POINT_AND_CLICK_INSPECT_OBJECT = 4204,
	## The player applies or uses an object.
	POINT_AND_CLICK_USE_OBJECT = 4205,
	## The player begins panning the view.
	POINT_AND_CLICK_START_PAN_VIEW = 4206,
	## The player ends panning the view.
	POINT_AND_CLICK_END_PAN_VIEW = 4207,
	## The player selects a combat target.
	COMBAT_SELECT_TARGET = 4300,
	## The player initiates an attack.
	COMBAT_INITIATE_ATTACK = 4301,
	## The player performs a defensive action.
	COMBAT_DEFEND = 4302,
	## The player attempts to evade an attack.
	COMBAT_EVADE = 4303,
	## The player uses a combat ability.
	COMBAT_USE_ABILITY = 4304,
	## The player begins aiming.
	COMBAT_START_AIM = 4305,
	## The player finishes aiming.
	COMBAT_END_AIM = 4306,
	## The player begins moving.
	NAVIGATION_START_MOVEMENT = 4400,
	## The player stops moving.
	NAVIGATION_END_MOVEMENT = 4401,
	## The player enters a defined area.
	NAVIGATION_ENTER_AREA = 4402,
	## The player exits a defined area.
	NAVIGATION_EXIT_AREA = 4403,
	## The player sets a movement destination.
	NAVIGATION_SET_DESTINATION = 4404,
	## The player snaps to a specific location.
	NAVIGATION_SNAP_TO_LOCATION = 4405,
	## The player advances time.
	NAVIGATION_ADVANCE_TIME = 4406,
	## The player purchases a resource or item.
	RESOURCE_MANAGEMENT_BUY = 4500,
	## The player sells a resource or item.
	RESOURCE_MANAGEMENT_SELL = 4501,
	## The player stores a resource or item.
	RESOURCE_MANAGEMENT_STORE = 4502,
	## The player collects or acquires a resource.
	RESOURCE_MANAGEMENT_COLLECT = 4503,
	## The player uses or consumes a resource.
	RESOURCE_MANAGEMENT_USE_RESOURCE = 4504,
	## The player loses a resource.
	RESOURCE_MANAGEMENT_LOSE_RESOURCE = 4505,
	## The player discards a resource.
	RESOURCE_MANAGEMENT_DISCARD_RESOURCE = 4506,
	## The player allocates a resource.
	RESOURCE_MANAGEMENT_ALLOCATE_RESOURCE = 4507,
	## The player converts one resource into another.
	RESOURCE_MANAGEMENT_CONVERT_RESOURCE = 4508,
	## The player assigns an entity or resource.
	SIMULATION_ASSIGN = 4600,
	## The player removes an assignment.
	SIMULATION_UNASSIGN = 4601,
	## The player sets a priority value.
	SIMULATION_SET_PRIORITY = 4602,
	## The player adjusts a simulation parameter.
	SIMULATION_ADJUST_PARAMETER = 4603,
	## The player schedules a simulation action.
	SIMULATION_SCHEDULE_ACTION = 4604,
	## The player pauses the simulation.
	SIMULATION_PAUSE_SIMULATION = 4605,
	## The player resumes the simulation.
	SIMULATION_RESUME_SIMULATION = 4606,
	## The player requests the current simulation state.
	SIMULATION_REQUEST_CURRENT_STATE = 4607,
	## The player selects a segment or subsegment.
	INTERFACE_STRUCTURAL_NAVIGATION_SELECT_SEGMENT = 4700,
	## The player opens an in-game interface element.
	INTERFACE_STRUCTURAL_NAVIGATION_OPEN_INTERFACE = 4701,
	## The player closes an in-game interface element.
	INTERFACE_STRUCTURAL_NAVIGATION_CLOSE_INTERFACE = 4702,
	## The player navigates to a different in-game screen.
	INTERFACE_STRUCTURAL_NAVIGATION_NAVIGATE_TO_SCREEN = 4703,
	## The player returns to the previous in-game screen.
	INTERFACE_STRUCTURAL_NAVIGATION_RETURN_TO_PREVIOUS_SCREEN = 4704,
	## The player selects an interface item.
	INTERFACE_STRUCTURAL_NAVIGATION_SELECT_ITEM = 4705,
	## The player confirms a selection.
	INTERFACE_STRUCTURAL_NAVIGATION_CONFIRM_SELECTION = 4706,
	## The player cancels a selection.
	INTERFACE_STRUCTURAL_NAVIGATION_CANCEL_SELECTION = 4707,
	## The player switches views.
	INTERFACE_STRUCTURAL_NAVIGATION_SWITCH_VIEW = 4708,
	## The player toggles an overlay.
	INTERFACE_STRUCTURAL_NAVIGATION_TOGGLE_OVERLAY = 4709,
}

enum OtherHumanPlayerAction {
	## Mirrors 4100: The player picks up or grabs an object.
	PUZZLE_CONSTRUCTED_RESPONSE_PICK_UP_OBJECT = 5100,
	## Mirrors 4101: The player places an object in a valid location/configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_PLACE_OBJECT_VALID = 5101,
	## Mirrors 4102: The player attempts to place an object in an invalid location/configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_PLACE_OBJECT_INVALID = 5102,
	## Mirrors 4103: The player removes an object from its current placement.
	PUZZLE_CONSTRUCTED_RESPONSE_REMOVE_OBJECT = 5103,
	## Mirrors 4104: The player begins rotating an object.
	PUZZLE_CONSTRUCTED_RESPONSE_START_ROTATE_OBJECT = 5104,
	## Mirrors 4105: The player finishes rotating an object.
	PUZZLE_CONSTRUCTED_RESPONSE_END_ROTATE_OBJECT = 5105,
	## Mirrors 4106: The player previews a potential object placement.
	PUZZLE_CONSTRUCTED_RESPONSE_PREVIEW_PLACEMENT = 5106,
	## Mirrors 4107: The player modifies an object’s state or configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_MODIFY_OBJECT = 5107,
	## Mirrors 4200: The player selects an object.
	POINT_AND_CLICK_SELECT_OBJECT = 5200,
	## Mirrors 4201: The player deselects an object.
	POINT_AND_CLICK_DESELECT_OBJECT = 5201,
	## Mirrors 4202: The player activates or triggers an object.
	POINT_AND_CLICK_ACTIVATE_OBJECT = 5202,
	## Mirrors 4203: The player changes an object’s state through interaction.
	POINT_AND_CLICK_CHANGE_OBJECT_STATE = 5203,
	## Mirrors 4204: The player inspects or examines an object.
	POINT_AND_CLICK_INSPECT_OBJECT = 5204,
	## Mirrors 4205: The player applies or uses an object.
	POINT_AND_CLICK_USE_OBJECT = 5205,
	## Mirrors 4206: The player begins panning the view.
	POINT_AND_CLICK_START_PAN_VIEW = 5206,
	## Mirrors 4207: The player ends panning the view.
	POINT_AND_CLICK_END_PAN_VIEW = 5207,
	## Mirrors 4300: The player selects a combat target.
	COMBAT_SELECT_TARGET = 5300,
	## Mirrors 4301: The player initiates an attack.
	COMBAT_INITIATE_ATTACK = 5301,
	## Mirrors 4302: The player performs a defensive action.
	COMBAT_DEFEND = 5302,
	## Mirrors 4303: The player attempts to evade an attack.
	COMBAT_EVADE = 5303,
	## Mirrors 4304: The player uses a combat ability.
	COMBAT_USE_ABILITY = 5304,
	## Mirrors 4305: The player begins aiming.
	COMBAT_START_AIM = 5305,
	## Mirrors 4306: The player finishes aiming.
	COMBAT_END_AIM = 5306,
	## Mirrors 4400: The player begins moving.
	NAVIGATION_START_MOVEMENT = 5400,
	## Mirrors 4401: The player stops moving.
	NAVIGATION_END_MOVEMENT = 5401,
	## Mirrors 4402: The player enters a defined area.
	NAVIGATION_ENTER_AREA = 5402,
	## Mirrors 4403: The player exits a defined area.
	NAVIGATION_EXIT_AREA = 5403,
	## Mirrors 4404: The player sets a movement destination.
	NAVIGATION_SET_DESTINATION = 5404,
	## Mirrors 4405: The player snaps to a specific location.
	NAVIGATION_SNAP_TO_LOCATION = 5405,
	## Mirrors 4406: The player advances time.
	NAVIGATION_ADVANCE_TIME = 5406,
	## Mirrors 4500: The player purchases a resource or item.
	RESOURCE_MANAGEMENT_BUY = 5500,
	## Mirrors 4501: The player sells a resource or item.
	RESOURCE_MANAGEMENT_SELL = 5501,
	## Mirrors 4502: The player stores a resource or item.
	RESOURCE_MANAGEMENT_STORE = 5502,
	## Mirrors 4503: The player collects or acquires a resource.
	RESOURCE_MANAGEMENT_COLLECT = 5503,
	## Mirrors 4504: The player uses or consumes a resource.
	RESOURCE_MANAGEMENT_USE_RESOURCE = 5504,
	## Mirrors 4505: The player loses a resource.
	RESOURCE_MANAGEMENT_LOSE_RESOURCE = 5505,
	## Mirrors 4506: The player discards a resource.
	RESOURCE_MANAGEMENT_DISCARD_RESOURCE = 5506,
	## Mirrors 4507: The player allocates a resource.
	RESOURCE_MANAGEMENT_ALLOCATE_RESOURCE = 5507,
	## Mirrors 4508: The player converts one resource into another.
	RESOURCE_MANAGEMENT_CONVERT_RESOURCE = 5508,
	## Mirrors 4600: The player assigns an entity or resource.
	SIMULATION_ASSIGN = 5600,
	## Mirrors 4601: The player removes an assignment.
	SIMULATION_UNASSIGN = 5601,
	## Mirrors 4602: The player sets a priority value.
	SIMULATION_SET_PRIORITY = 5602,
	## Mirrors 4603: The player adjusts a simulation parameter.
	SIMULATION_ADJUST_PARAMETER = 5603,
	## Mirrors 4604: The player schedules a simulation action.
	SIMULATION_SCHEDULE_ACTION = 5604,
	## Mirrors 4605: The player pauses the simulation.
	SIMULATION_PAUSE_SIMULATION = 5605,
	## Mirrors 4606: The player resumes the simulation.
	SIMULATION_RESUME_SIMULATION = 5606,
	## Mirrors 4607: The player requests the current simulation state.
	SIMULATION_REQUEST_CURRENT_STATE = 5607,
	## Mirrors 4700: The player selects a segment or subsegment.
	INTERFACE_STRUCTURAL_NAVIGATION_SELECT_SEGMENT = 5700,
	## Mirrors 4701: The player opens an in-game interface element.
	INTERFACE_STRUCTURAL_NAVIGATION_OPEN_INTERFACE = 5701,
	## Mirrors 4702: The player closes an in-game interface element.
	INTERFACE_STRUCTURAL_NAVIGATION_CLOSE_INTERFACE = 5702,
	## Mirrors 4703: The player navigates to a different in-game screen.
	INTERFACE_STRUCTURAL_NAVIGATION_NAVIGATE_TO_SCREEN = 5703,
	## Mirrors 4704: The player returns to the previous in-game screen.
	INTERFACE_STRUCTURAL_NAVIGATION_RETURN_TO_PREVIOUS_SCREEN = 5704,
	## Mirrors 4705: The player selects an interface item.
	INTERFACE_STRUCTURAL_NAVIGATION_SELECT_ITEM = 5705,
	## Mirrors 4706: The player confirms a selection.
	INTERFACE_STRUCTURAL_NAVIGATION_CONFIRM_SELECTION = 5706,
	## Mirrors 4707: The player cancels a selection.
	INTERFACE_STRUCTURAL_NAVIGATION_CANCEL_SELECTION = 5707,
	## Mirrors 4708: The player switches views.
	INTERFACE_STRUCTURAL_NAVIGATION_SWITCH_VIEW = 5708,
	## Mirrors 4709: The player toggles an overlay.
	INTERFACE_STRUCTURAL_NAVIGATION_TOGGLE_OVERLAY = 5709,
}

enum SystemControlledActorAction {
	## Mirrors 4100: The player picks up or grabs an object.
	PUZZLE_CONSTRUCTED_RESPONSE_PICK_UP_OBJECT = 6100,
	## Mirrors 4101: The player places an object in a valid location/configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_PLACE_OBJECT_VALID = 6101,
	## Mirrors 4102: The player attempts to place an object in an invalid location/configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_PLACE_OBJECT_INVALID = 6102,
	## Mirrors 4103: The player removes an object from its current placement.
	PUZZLE_CONSTRUCTED_RESPONSE_REMOVE_OBJECT = 6103,
	## Mirrors 4104: The player begins rotating an object.
	PUZZLE_CONSTRUCTED_RESPONSE_START_ROTATE_OBJECT = 6104,
	## Mirrors 4105: The player finishes rotating an object.
	PUZZLE_CONSTRUCTED_RESPONSE_END_ROTATE_OBJECT = 6105,
	## Mirrors 4106: The player previews a potential object placement.
	PUZZLE_CONSTRUCTED_RESPONSE_PREVIEW_PLACEMENT = 6106,
	## Mirrors 4107: The player modifies an object’s state or configuration.
	PUZZLE_CONSTRUCTED_RESPONSE_MODIFY_OBJECT = 6107,
	## Mirrors 4200: The player selects an object.
	POINT_AND_CLICK_SELECT_OBJECT = 6200,
	## Mirrors 4201: The player deselects an object.
	POINT_AND_CLICK_DESELECT_OBJECT = 6201,
	## Mirrors 4202: The player activates or triggers an object.
	POINT_AND_CLICK_ACTIVATE_OBJECT = 6202,
	## Mirrors 4203: The player changes an object’s state through interaction.
	POINT_AND_CLICK_CHANGE_OBJECT_STATE = 6203,
	## Mirrors 4204: The player inspects or examines an object.
	POINT_AND_CLICK_INSPECT_OBJECT = 6204,
	## Mirrors 4205: The player applies or uses an object.
	POINT_AND_CLICK_USE_OBJECT = 6205,
	## Mirrors 4206: The player begins panning the view.
	POINT_AND_CLICK_START_PAN_VIEW = 6206,
	## Mirrors 4207: The player ends panning the view.
	POINT_AND_CLICK_END_PAN_VIEW = 6207,
	## Mirrors 4300: The player selects a combat target.
	COMBAT_SELECT_TARGET = 6300,
	## Mirrors 4301: The player initiates an attack.
	COMBAT_INITIATE_ATTACK = 6301,
	## Mirrors 4302: The player performs a defensive action.
	COMBAT_DEFEND = 6302,
	## Mirrors 4303: The player attempts to evade an attack.
	COMBAT_EVADE = 6303,
	## Mirrors 4304: The player uses a combat ability.
	COMBAT_USE_ABILITY = 6304,
	## Mirrors 4305: The player begins aiming.
	COMBAT_START_AIM = 6305,
	## Mirrors 4306: The player finishes aiming.
	COMBAT_END_AIM = 6306,
	## Mirrors 4400: The player begins moving.
	NAVIGATION_START_MOVEMENT = 6400,
	## Mirrors 4401: The player stops moving.
	NAVIGATION_END_MOVEMENT = 6401,
	## Mirrors 4402: The player enters a defined area.
	NAVIGATION_ENTER_AREA = 6402,
	## Mirrors 4403: The player exits a defined area.
	NAVIGATION_EXIT_AREA = 6403,
	## Mirrors 4404: The player sets a movement destination.
	NAVIGATION_SET_DESTINATION = 6404,
	## Mirrors 4405: The player snaps to a specific location.
	NAVIGATION_SNAP_TO_LOCATION = 6405,
	## Mirrors 4406: The player advances time.
	NAVIGATION_ADVANCE_TIME = 6406,
	## Mirrors 4500: The player purchases a resource or item.
	RESOURCE_MANAGEMENT_BUY = 6500,
	## Mirrors 4501: The player sells a resource or item.
	RESOURCE_MANAGEMENT_SELL = 6501,
	## Mirrors 4502: The player stores a resource or item.
	RESOURCE_MANAGEMENT_STORE = 6502,
	## Mirrors 4503: The player collects or acquires a resource.
	RESOURCE_MANAGEMENT_COLLECT = 6503,
	## Mirrors 4504: The player uses or consumes a resource.
	RESOURCE_MANAGEMENT_USE_RESOURCE = 6504,
	## Mirrors 4505: The player loses a resource.
	RESOURCE_MANAGEMENT_LOSE_RESOURCE = 6505,
	## Mirrors 4506: The player discards a resource.
	RESOURCE_MANAGEMENT_DISCARD_RESOURCE = 6506,
	## Mirrors 4507: The player allocates a resource.
	RESOURCE_MANAGEMENT_ALLOCATE_RESOURCE = 6507,
	## Mirrors 4508: The player converts one resource into another.
	RESOURCE_MANAGEMENT_CONVERT_RESOURCE = 6508,
	## Mirrors 4600: The player assigns an entity or resource.
	SIMULATION_ASSIGN = 6600,
	## Mirrors 4601: The player removes an assignment.
	SIMULATION_UNASSIGN = 6601,
	## Mirrors 4602: The player sets a priority value.
	SIMULATION_SET_PRIORITY = 6602,
	## Mirrors 4603: The player adjusts a simulation parameter.
	SIMULATION_ADJUST_PARAMETER = 6603,
	## Mirrors 4604: The player schedules a simulation action.
	SIMULATION_SCHEDULE_ACTION = 6604,
	## Mirrors 4605: The player pauses the simulation.
	SIMULATION_PAUSE_SIMULATION = 6605,
	## Mirrors 4606: The player resumes the simulation.
	SIMULATION_RESUME_SIMULATION = 6606,
	## Mirrors 4607: The player requests the current simulation state.
	SIMULATION_REQUEST_CURRENT_STATE = 6607,
	## Mirrors 4700: The player selects a segment or subsegment.
	INTERFACE_STRUCTURAL_NAVIGATION_SELECT_SEGMENT = 6700,
	## Mirrors 4701: The player opens an in-game interface element.
	INTERFACE_STRUCTURAL_NAVIGATION_OPEN_INTERFACE = 6701,
	## Mirrors 4702: The player closes an in-game interface element.
	INTERFACE_STRUCTURAL_NAVIGATION_CLOSE_INTERFACE = 6702,
	## Mirrors 4703: The player navigates to a different in-game screen.
	INTERFACE_STRUCTURAL_NAVIGATION_NAVIGATE_TO_SCREEN = 6703,
	## Mirrors 4704: The player returns to the previous in-game screen.
	INTERFACE_STRUCTURAL_NAVIGATION_RETURN_TO_PREVIOUS_SCREEN = 6704,
	## Mirrors 4705: The player selects an interface item.
	INTERFACE_STRUCTURAL_NAVIGATION_SELECT_ITEM = 6705,
	## Mirrors 4706: The player confirms a selection.
	INTERFACE_STRUCTURAL_NAVIGATION_CONFIRM_SELECTION = 6706,
	## Mirrors 4707: The player cancels a selection.
	INTERFACE_STRUCTURAL_NAVIGATION_CANCEL_SELECTION = 6707,
	## Mirrors 4708: The player switches views.
	INTERFACE_STRUCTURAL_NAVIGATION_SWITCH_VIEW = 6708,
	## Mirrors 4709: The player toggles an overlay.
	INTERFACE_STRUCTURAL_NAVIGATION_TOGGLE_OVERLAY = 6709,
}

enum SystemAction {
	## The system introduces a new entity into active gameplay.
	ENTITY_RESOURCE_CHANGES_CREATE_ENTITY = 7110,
	## The system removes an entity from active gameplay.
	ENTITY_RESOURCE_CHANGES_REMOVE_ENTITY = 7111,
	## The system changes an entity’s form, type, or role while preserving continuity within gameplay.
	ENTITY_RESOURCE_CHANGES_TRANSFORM_ENTITY = 7112,
	## The system increases the value of a gameplay resource.
	ENTITY_RESOURCE_CHANGES_INCREMENT_RESOURCE = 7120,
	## The system decreases the value of a gameplay resource.
	ENTITY_RESOURCE_CHANGES_DECREMENT_RESOURCE = 7121,
	## The system advances or updates a counter or timer variable.
	ENTITY_RESOURCE_CHANGES_UPDATE_COUNTER = 7122,
	## The system initiates continuous movement of an entity.
	MOVEMENT_SPATIAL_CHANGE_START_ENTITY_MOVEMENT = 7200,
	## The system ends continuous movement of an entity.
	MOVEMENT_SPATIAL_CHANGE_END_ENTITY_MOVEMENT = 7201,
	## The system instantly relocates an entity to a new position.
	MOVEMENT_SPATIAL_CHANGE_REPOSITION_ENTITY = 7202,
	## The system initiates movement of an environmental gameplay element.
	MOVEMENT_SPATIAL_CHANGE_START_ENVIRONMENT_MOVEMENT = 7203,
	## The system ends movement of an environmental gameplay element.
	MOVEMENT_SPATIAL_CHANGE_END_ENVIRONMENT_MOVEMENT = 7204,
	## The system instantly relocates an environmental gameplay element.
	MOVEMENT_SPATIAL_CHANGE_REPOSITION_ENVIRONMENT_ELEMENT = 7205,
	## The system initializes a simulation process.
	SIMULATION_EXECUTION_INITIALIZE_SIMULATION = 7300,
	## The system begins executing a simulation.
	SIMULATION_EXECUTION_START_SIMULATION = 7301,
	## The system pauses simulation execution.
	SIMULATION_EXECUTION_PAUSE_SIMULATION = 7302,
	## The system resumes a paused simulation.
	SIMULATION_EXECUTION_RESUME_SIMULATION = 7303,
	## The system advances the simulation by a discrete step or interval.
	SIMULATION_EXECUTION_ADVANCE_SIMULATION = 7304,
	## The system resets the simulation to a baseline state.
	SIMULATION_EXECUTION_RESET_SIMULATION = 7305,
	## The system terminates simulation execution.
	SIMULATION_EXECUTION_TERMINATE_SIMULATION = 7306,
	## The system makes gameplay-relevant information visible or discoverable to the player.
	INFORMATION_VISIBILITY_REVEAL_INFORMATION = 7400,
	## The system hides gameplay-relevant information from the player.
	INFORMATION_VISIBILITY_CONCEAL_INFORMATION = 7401,
	## The system displays an in-game interface element.
	IN_GAME_INTERFACE_STATE_DISPLAY_INTERFACE_ELEMENT = 7500,
	## The system hides an in-game interface element.
	IN_GAME_INTERFACE_STATE_HIDE_INTERFACE_ELEMENT = 7501,
	## The system updates the content or state of an interface element.
	IN_GAME_INTERFACE_STATE_UPDATE_INTERFACE_ELEMENT = 7502,
	## The system enables interaction with an interface element.
	IN_GAME_INTERFACE_STATE_ENABLE_INTERFACE_ELEMENT = 7503,
	## The system disables interaction with an interface element.
	IN_GAME_INTERFACE_STATE_DISABLE_INTERFACE_ELEMENT = 7504,
	## The system begins emitting a gameplay-relevant audiovisual signal.
	SYSTEM_SIGNALING_START_SYSTEM_SIGNAL = 7600,
	## The system stops emitting a gameplay-relevant audiovisual signal.
	SYSTEM_SIGNALING_END_SYSTEM_SIGNAL = 7601,
	## The system changes the type or state of an active signal.
	SYSTEM_SIGNALING_CHANGE_SYSTEM_SIGNAL = 7602,
}
